version: "3.8"

services:
  api:
    build: .
    container_name: playbbit-api
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - hls_data:/tmp/hls
    networks:
      - playbbit-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  playbbit-network:
    external: true

volumes:
  hls_data:
    external: true
    name: infra_hls_data
