spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  server:
    connection-timeout: 300000
    tomcat:
      max-swallow-size: 500MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/${PLAYBBIT_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

minio:
  endpoint: ${MINIO_ENDPOINT}
  external-url: ${MINIO_EXTERNAL_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  region: ${MINIO_REGION:us-east-1}
  bucket: ${MINIO_BUCKET:pbs}

app:
  jwt:
    secret: ${JWT_SECRET}
  stream:
    ingest-base-url: "rtmp://localhost:1935/live"
